[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan view:cache'
]

[start]
cmd = 'chmod 777 storage -R && chmod 666 database/database.sqlite && php artisan serve --host=0.0.0.0 --port=$PORT'

